name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          ANALYTICS_CLIENT_URL: ${{ secrets.ANALYTICS_CLIENT_URL }}
          ANALYTICS_CLIENT_SECRET: ${{ secrets.ANALYTICS_CLIENT_SECRET }}
          ANALYTICS_CLIENT_ID: ${{ secrets.ANALYTICS_CLIENT_ID }}
